name: Get Citation Data

on:
  page_build: 
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r google_scholar_crawler/requirements.txt

      - name: Run crawler
        run: |
          cd google_scholar_crawler
          python main.py

      - name: Check for data changes
        run: |
          git fetch origin google-scholar-stats
          git diff origin/google-scholar-stats -- results/gs_data.json > diff.txt
          if [ -s diff.txt ]; then
            echo "Data has changed."
            echo "data_changed=true" >> $GITHUB_ENV
          else
            echo "No data changes."
            echo "data_changed=false" >> $GITHUB_ENV
          fi

      - name: Commit and push changes
        if: env.data_changed == 'true'
        run: |
          git config --local user.name "${GITHUB_ACTOR}"
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add results/gs_data.json results/gs_data_shieldsio.json
          git commit -m "Updated Citation Data"
          git push origin HEAD:google-scholar-stats
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
